apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: gitops-git-source
spec:
  type: git
  params:
  - name: url
    value: git@github.com:example/app-config.git
  - name: revision
    value: master
  - name: refspec
    value: refs/heads/master:refs/heads/master
---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-image
spec:
  type: image
  params: 
  - name: url
    value: "docker.example.com/app"
---
